/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem;

import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;

/**
 *
 * @author Janithri
 */
public class Helicopter extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Helicopter
     */
    private Observable observable;
    
    public Helicopter() {
         this.observable = observable.getInstance();
        initComponents();
         setResizable(false);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        sliderHeli = new javax.swing.JSlider();
        checkBoxPosition = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        spinnerSoldierHeli = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spinnerAmmoHeli = new javax.swing.JSpinner();
        area1 = new javax.swing.JLabel();
        txtMsgHeli = new javax.swing.JTextField();
        btnShootHeli = new javax.swing.JButton();
        btnMissileHeli = new javax.swing.JButton();
        btnLaserHeli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSendH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGetMsg3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel4.setRequestFocusEnabled(false);

        sliderHeli.setBackground(new java.awt.Color(153, 153, 255));
        sliderHeli.setMajorTickSpacing(20);
        sliderHeli.setMinorTickSpacing(10);
        sliderHeli.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderHeli.setPaintLabels(true);
        sliderHeli.setPaintTicks(true);
        sliderHeli.setValue(100);
        sliderHeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        checkBoxPosition.setBackground(new java.awt.Color(153, 153, 255));
        checkBoxPosition.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        checkBoxPosition.setText("Position");
        checkBoxPosition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPositionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel7.setText("Soldier count");

        spinnerSoldierHeli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel8.setText("Ammo count");

        spinnerAmmoHeli.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        area1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtMsgHeli.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtMsgHeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgHeliActionPerformed(evt);
            }
        });

        btnShootHeli.setBackground(new java.awt.Color(51, 102, 255));
        btnShootHeli.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnShootHeli.setText("Shoot");
        btnShootHeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShootHeli.setEnabled(false);
        btnShootHeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootHeliActionPerformed(evt);
            }
        });

        btnMissileHeli.setBackground(new java.awt.Color(51, 102, 255));
        btnMissileHeli.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnMissileHeli.setText("Missile Operation");
        btnMissileHeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMissileHeli.setEnabled(false);
        btnMissileHeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileHeliActionPerformed(evt);
            }
        });

        btnLaserHeli.setBackground(new java.awt.Color(51, 102, 255));
        btnLaserHeli.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnLaserHeli.setText("Laser Operation");
        btnLaserHeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaserHeli.setEnabled(false);
        btnLaserHeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaserHeliActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("HELICOPTER");

        txtSendH.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtSendH.setText("Send");
        txtSendH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSendH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSendHActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel5.setText("Fuel Count");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinnerAmmoHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(spinnerSoldierHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnShootHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMissileHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnLaserHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtMsgHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtSendH))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(checkBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMsgHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSendH))
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxPosition))
                    .addComponent(sliderHeli, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addComponent(btnShootHeli)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerSoldierHeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerAmmoHeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMissileHeli)
                        .addGap(18, 18, 18)
                        .addComponent(btnLaserHeli)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        txtGetMsg3.setColumns(20);
        txtGetMsg3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtGetMsg3.setRows(5);
        txtGetMsg3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(txtGetMsg3);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel3.setText("                   Instruction");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionActionPerformed

    private void txtMsgHeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgHeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsgHeliActionPerformed

    private void txtSendHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSendHActionPerformed
        // TODO add your handling code here:
        String text = "Helicopter : " +txtMsgHeli.getText();
        System.out.println(text);
        Observable.getInstance().setMessagesToHeadOfz(text);
        txtMsgHeli.setText("");
    }//GEN-LAST:event_txtSendHActionPerformed

    private void btnShootHeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootHeliActionPerformed
        // TODO add your handling code here:
        int count = (int) spinnerAmmoHeli.getValue();
        spinnerAmmoHeli.setValue(count-5);
    }//GEN-LAST:event_btnShootHeliActionPerformed

    private void btnMissileHeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileHeliActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Helicopter : Missile Operation is COMPLETED");
    }//GEN-LAST:event_btnMissileHeliActionPerformed

    private void btnLaserHeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaserHeliActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Helicopter : Laser Operation is COMPLETED");
    }//GEN-LAST:event_btnLaserHeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helicopter().setVisible(true);
            }
        });
    }
    //Override
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area1;
    private javax.swing.JButton btnLaserHeli;
    private javax.swing.JButton btnMissileHeli;
    private javax.swing.JButton btnShootHeli;
    private javax.swing.JCheckBox checkBoxPosition;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JSlider sliderHeli;
    public static javax.swing.JSpinner spinnerAmmoHeli;
    public static javax.swing.JSpinner spinnerSoldierHeli;
    private javax.swing.JTextArea txtGetMsg3;
    private javax.swing.JTextField txtMsgHeli;
    private javax.swing.JButton txtSendH;
    // End of variables declaration//GEN-END:variables

    public void AreaClearUpdate(boolean area){
        if(area){
         area1.setText("Area Clear");
         }else{
         area1.setText("Area NOT Clear");
        }
    }
    
    
     public void getSliderValue(int value){
        // System.out.println(value);
         if(checkBoxPosition.isSelected()){
        if(value >= 65){
            btnShootHeli.setEnabled(true);
            btnMissileHeli.setEnabled(true);
            btnLaserHeli.setEnabled(true);
        } else if(value >= 40){
            btnShootHeli.setEnabled(true);
            btnMissileHeli.setEnabled(true);
            btnLaserHeli.setEnabled(false);
        } else if(value >= 20){
            btnShootHeli.setEnabled(true);
            btnMissileHeli.setEnabled(false);
            btnLaserHeli.setEnabled(false);
        } else {
            btnShootHeli.setEnabled(false);
            btnMissileHeli.setEnabled(false);
            btnLaserHeli.setEnabled(false);
        }
    } else {
        btnShootHeli.setEnabled(false);
        btnMissileHeli.setEnabled(false);
        btnLaserHeli.setEnabled(false);    
    }
  }
     
     
    public void sendMessagesToDefences(String message){
        txtGetMsg3.append("Head Office : "+message+"\n");
    }
    public void sendMessagesToHeadOfz(String text){}
    

}
