/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem;
import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;

/**
 *
 * @author Janithri
 */
public class Submarine extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Submarine
     */
    
     private Observable observable;
     
    public Submarine() {
        this.observable = observable.getInstance();
        
        initComponents();
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        checkBoxSub = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        spinnerSoldierSub = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        area3 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        sliderFuelSub = new javax.swing.JSlider();
        FuelSub = new javax.swing.JLabel();
        btnSendSub = new javax.swing.JButton();
        btnShootSub = new javax.swing.JButton();
        btnTridentSub = new javax.swing.JButton();
        btnSonarSub = new javax.swing.JButton();
        btnTomahawkSub = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spinnerAmmoSub = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGetMsg1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N

        checkBoxSub.setBackground(new java.awt.Color(153, 153, 255));
        checkBoxSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        checkBoxSub.setText("Position");
        checkBoxSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBoxSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSubActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel7.setText("Soldier count");

        spinnerSoldierSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText("Ammo count");

        area3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });

        sliderFuelSub.setBackground(new java.awt.Color(153, 153, 255));
        sliderFuelSub.setMajorTickSpacing(20);
        sliderFuelSub.setMinorTickSpacing(10);
        sliderFuelSub.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderFuelSub.setPaintLabels(true);
        sliderFuelSub.setPaintTicks(true);
        sliderFuelSub.setValue(100);
        sliderFuelSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        FuelSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        FuelSub.setText("Fuel Count");

        btnSendSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnSendSub.setText("Send");
        btnSendSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSendSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSubActionPerformed(evt);
            }
        });

        btnShootSub.setBackground(new java.awt.Color(51, 102, 255));
        btnShootSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnShootSub.setText("Shoot");
        btnShootSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShootSub.setEnabled(false);
        btnShootSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootSubActionPerformed(evt);
            }
        });

        btnTridentSub.setBackground(new java.awt.Color(51, 102, 255));
        btnTridentSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnTridentSub.setText("Trident-2 ");
        btnTridentSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTridentSub.setEnabled(false);
        btnTridentSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTridentSubActionPerformed(evt);
            }
        });

        btnSonarSub.setBackground(new java.awt.Color(51, 102, 255));
        btnSonarSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnSonarSub.setText("Sonar Operation");
        btnSonarSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSonarSub.setEnabled(false);
        btnSonarSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonarSubActionPerformed(evt);
            }
        });

        btnTomahawkSub.setBackground(new java.awt.Color(51, 102, 255));
        btnTomahawkSub.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnTomahawkSub.setText("Tomahawk Missile");
        btnTomahawkSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTomahawkSub.setEnabled(false);
        btnTomahawkSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomahawkSubActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("SUBMARINE");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel10.setText("Ammo count");

        spinnerAmmoSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShootSub, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTridentSub, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSonarSub, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTomahawkSub, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSendSub))
                                    .addComponent(area3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(checkBoxSub, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(FuelSub, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sliderFuelSub, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spinnerAmmoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerSoldierSub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(area3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendSub))
                        .addGap(44, 44, 44)
                        .addComponent(checkBoxSub)
                        .addGap(18, 18, 18)
                        .addComponent(btnShootSub)
                        .addGap(18, 18, 18)
                        .addComponent(btnSonarSub)
                        .addGap(18, 18, 18)
                        .addComponent(btnTomahawkSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTridentSub))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(sliderFuelSub, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FuelSub)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerSoldierSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerAmmoSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        txtGetMsg1.setColumns(20);
        txtGetMsg1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtGetMsg1.setRows(5);
        jScrollPane2.setViewportView(txtGetMsg1);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel9.setText("                   Instruction");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSubActionPerformed

    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubActionPerformed

    private void btnSendSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSubActionPerformed
        String text = "Submarine : "+txtSub.getText();
        System.out.println(text);
        Observable.getInstance().setMessagesToHeadOfz(text);
        txtSub.setText("");
    }//GEN-LAST:event_btnSendSubActionPerformed

    private void btnTridentSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTridentSubActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Submarine : Trident-2 Operation is COMPLETED");
    }//GEN-LAST:event_btnTridentSubActionPerformed

    private void btnTomahawkSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomahawkSubActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Submarine : Tomhawak Missile Operation is COMPLETED");
    }//GEN-LAST:event_btnTomahawkSubActionPerformed

    private void btnSonarSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonarSubActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Submarine : Sonar Operation is COMPLETED");
    }//GEN-LAST:event_btnSonarSubActionPerformed

    private void btnShootSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootSubActionPerformed
        // TODO add your handling code here:
        int count = (int) spinnerAmmoSub.getValue();
        spinnerAmmoSub.setValue(count-5);
    }//GEN-LAST:event_btnShootSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FuelSub;
    private javax.swing.JLabel area3;
    private javax.swing.JButton btnSendSub;
    private javax.swing.JButton btnShootSub;
    private javax.swing.JButton btnSonarSub;
    private javax.swing.JButton btnTomahawkSub;
    private javax.swing.JButton btnTridentSub;
    private javax.swing.JCheckBox checkBoxSub;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner6;
    public static javax.swing.JSlider sliderFuelSub;
    public static javax.swing.JSpinner spinnerAmmoSub;
    public static javax.swing.JSpinner spinnerSoldierSub;
    private javax.swing.JTextArea txtGetMsg1;
    private javax.swing.JTextField txtSub;
    // End of variables declaration//GEN-END:variables

 
     //Override
    public void AreaClearUpdate(boolean area){
        if(area){
         area3.setText("Area Clear");        
         }else{
         area3.setText("Area NOT Clear");
        }
    }

    @Override
   public void getSliderValue(int value){
        // System.out.println(value);
         if(checkBoxSub.isSelected()){
        if(value >= 85){
            btnShootSub.setEnabled(true);
            btnSonarSub.setEnabled(true);
            btnTomahawkSub.setEnabled(true);
            btnTridentSub.setEnabled(true);             
        } else if(value >= 65){
            btnShootSub.setEnabled(true);
            btnSonarSub.setEnabled(true);
            btnTomahawkSub.setEnabled(true);
            btnTridentSub.setEnabled(false);
        } else if(value >= 40){
            btnShootSub.setEnabled(true);
            btnSonarSub.setEnabled(true);
            btnTomahawkSub.setEnabled(false);
            btnTridentSub.setEnabled(false);
        } else if(value >= 20){
            btnShootSub.setEnabled(true);
            btnSonarSub.setEnabled(false);
            btnTomahawkSub.setEnabled(false);
            btnTridentSub.setEnabled(false);
        } else {
            btnShootSub.setEnabled(false);
            btnSonarSub.setEnabled(false);
            btnTomahawkSub.setEnabled(false);
            btnTridentSub.setEnabled(false);
        }
    } else {
        btnShootSub.setEnabled(false);
            btnSonarSub.setEnabled(false);
            btnTomahawkSub.setEnabled(false);
            btnTridentSub.setEnabled(false);       
    }
   }
    
    
    public void sendMessagesToDefences(String message){
        txtGetMsg1.append("Head Office : "+message+"\n");
    }
    
    public void sendMessagesToHeadOfz(String text){}

}
