/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem;

import java.util.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;

/**
 *
 * @author Janithri
 */
 class Tank extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form Tank
     */
     private Observable observable;
    
   
     Tank() {
         this.observable = observable.getInstance();
        initComponents();
         setResizable(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        sliderFuelTank = new javax.swing.JSlider();
        ckeckBoxTank = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        SpinnerSoldierTank = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        SpinnerAmmoSub = new javax.swing.JSpinner();
        area2 = new javax.swing.JLabel();
        txtTank = new javax.swing.JTextField();
        btnShootTank = new javax.swing.JButton();
        btnMissileTank = new javax.swing.JButton();
        btnRedarTank = new javax.swing.JButton();
        btnRotateTank = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSendTank = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGetMsg2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        sliderFuelTank.setBackground(new java.awt.Color(153, 153, 255));
        sliderFuelTank.setMajorTickSpacing(20);
        sliderFuelTank.setMinorTickSpacing(10);
        sliderFuelTank.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderFuelTank.setPaintLabels(true);
        sliderFuelTank.setPaintTicks(true);
        sliderFuelTank.setValue(100);
        sliderFuelTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ckeckBoxTank.setBackground(new java.awt.Color(153, 153, 255));
        ckeckBoxTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ckeckBoxTank.setText("Position");
        ckeckBoxTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ckeckBoxTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckeckBoxTankActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel7.setText("Soldier count");

        SpinnerSoldierTank.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel8.setText("Ammo count");

        SpinnerAmmoSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        area2.setBackground(new java.awt.Color(255, 255, 0));
        area2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTankActionPerformed(evt);
            }
        });

        btnShootTank.setBackground(new java.awt.Color(51, 102, 255));
        btnShootTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnShootTank.setText("Shoot");
        btnShootTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShootTank.setEnabled(false);
        btnShootTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootTankActionPerformed(evt);
            }
        });

        btnMissileTank.setBackground(new java.awt.Color(51, 102, 255));
        btnMissileTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnMissileTank.setText("Missile Operation");
        btnMissileTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMissileTank.setEnabled(false);
        btnMissileTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileTankActionPerformed(evt);
            }
        });

        btnRedarTank.setBackground(new java.awt.Color(51, 102, 255));
        btnRedarTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnRedarTank.setText("Redar Operation ");
        btnRedarTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedarTank.setEnabled(false);
        btnRedarTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedarTankActionPerformed(evt);
            }
        });

        btnRotateTank.setBackground(new java.awt.Color(51, 102, 255));
        btnRotateTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnRotateTank.setText("Rotate Shooting");
        btnRotateTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRotateTank.setEnabled(false);
        btnRotateTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateTankActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 102, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("TANK");

        btnSendTank.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnSendTank.setText("Send");
        btnSendTank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSendTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendTankActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        jLabel5.setText("Fuel Count");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnShootTank, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMissileTank, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRedarTank, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRotateTank, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtTank, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnSendTank))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(ckeckBoxTank, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderFuelTank, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SpinnerAmmoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(SpinnerSoldierTank, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTank, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendTank))
                        .addGap(38, 38, 38)
                        .addComponent(ckeckBoxTank))
                    .addComponent(sliderFuelTank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerSoldierTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerAmmoSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnShootTank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMissileTank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRedarTank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRotateTank)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        txtGetMsg2.setColumns(20);
        txtGetMsg2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        txtGetMsg2.setRows(5);
        jScrollPane2.setViewportView(txtGetMsg2);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel9.setText("                   Instruction");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckeckBoxTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckeckBoxTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckeckBoxTankActionPerformed

    private void txtTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTankActionPerformed

    private void btnSendTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendTankActionPerformed
        String text = "Tank : "+txtTank.getText();
        System.out.println(text);
        Observable.getInstance().setMessagesToHeadOfz(text);
        txtTank.setText("");
    }//GEN-LAST:event_btnSendTankActionPerformed

    private void btnShootTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootTankActionPerformed
        // TODO add your handling code here:
        int count = (int) SpinnerAmmoSub.getValue();
        SpinnerAmmoSub.setValue(count-5);
    }//GEN-LAST:event_btnShootTankActionPerformed

    private void btnMissileTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileTankActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Tank : Missile Operation is COMPLETED");
    }//GEN-LAST:event_btnMissileTankActionPerformed

    private void btnRedarTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedarTankActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Tank : Redar Operation is COMPLETED");
    }//GEN-LAST:event_btnRedarTankActionPerformed

    private void btnRotateTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateTankActionPerformed
        // TODO add your handling code here:
        Observable.getInstance().setMessagesToHeadOfz("Tank : Rotate Shooting is COMPLETED");
    }//GEN-LAST:event_btnRotateTankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner SpinnerAmmoSub;
    public static javax.swing.JSpinner SpinnerSoldierTank;
    private javax.swing.JLabel area2;
    private javax.swing.JButton btnMissileTank;
    private javax.swing.JButton btnRedarTank;
    private javax.swing.JButton btnRotateTank;
    private javax.swing.JButton btnSendTank;
    private javax.swing.JButton btnShootTank;
    private javax.swing.JCheckBox ckeckBoxTank;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JSlider sliderFuelTank;
    private javax.swing.JTextArea txtGetMsg2;
    private javax.swing.JTextField txtTank;
    // End of variables declaration//GEN-END:variables

    
    //over ridding
    public void AreaClearUpdate(boolean area){
        if(area){
         area2.setText("Area Clear");
         }else{
         area2.setText("Area NOT Clear");
        }
    }

     public void getSliderValue(int value){
        // System.out.println(value);
         if(ckeckBoxTank.isSelected()){
        if(value >= 85){
            btnShootTank.setEnabled(true);
            btnMissileTank.setEnabled(true);
            btnRedarTank.setEnabled(true);
            btnRotateTank.setEnabled(true);             
        } else if(value >= 65){
            btnShootTank.setEnabled(true);
            btnMissileTank.setEnabled(true);
            btnRedarTank.setEnabled(true);
            btnRotateTank.setEnabled(false);
        } else if(value >= 40){
            btnShootTank.setEnabled(true);
            btnMissileTank.setEnabled(true);
            btnRedarTank.setEnabled(false);
            btnRotateTank.setEnabled(false);
        } else if(value >= 20){
            btnShootTank.setEnabled(true);
            btnMissileTank.setEnabled(false);
            btnRedarTank.setEnabled(false);
            btnRotateTank.setEnabled(false);
        } else {
            btnShootTank.setEnabled(false);
            btnMissileTank.setEnabled(false);
            btnRedarTank.setEnabled(false);
            btnRotateTank.setEnabled(false);
        }
    } else {
        btnShootTank.setEnabled(false);
        btnMissileTank.setEnabled(false);
        btnRedarTank.setEnabled(false);
        btnRotateTank.setEnabled(false);
    }
    }
    
     @Override
    public void sendMessagesToDefences(String message){
        txtGetMsg2.append("Head Office : "+message+"\n");
    }
    
        public void sendMessagesToHeadOfz(String text){}

 
 }
